version: "3"

services:
  app:
    image: docker.io/library/status-app:0.0.1-SNAPSHOT
    scale: 4
    ports:
      - "8080"

  gateway:
    image: openresty/openresty:alpine-fat
    volumes:
      - ./conf/nginx-balancer.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app

  geo-gateway:
    image: hla/nginx-geo:1.19.2
    ports:
      - "81:80"
    depends_on:
      - app