# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes: 
      - ./sql/1_schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./sql/2_data.sql:/docker-entrypoint-initdb.d/2_data.sql
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: P@ssw0rd

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080