version: '3.1'

services:

  db:
    image: percona
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: hla
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: hla
    ports:
      - '3306:3306'
    volumes:
      - /Users/Shared/Docker/percona/data:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf

  adminer:
    image: adminer
    ports:
      - '8080:8080'