version: "3"

services:
  redis-master:
    image: "bitnami/redis"
    container_name: redis-master
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=P@ssw0rd
    ports:
      - "6379"

  redis-replica:
    image: "bitnami/redis"
    environment:
      - REDIS_REPLICATION_MODE=replica
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=P@ssw0rd
      - REDIS_PASSWORD=P@ssw0rd
    ports:
      - "6379"
    depends_on:
      - redis-master

  redis-sentinel:
    image: "bitnami/redis-sentinel"
    environment:
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=P@ssw0rd
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
    depends_on:
      - redis-master
      - redis-replica
    ports:
      - "26379"

  app:
    image: docker.io/library/redis-sentinel:0.0.1-SNAPSHOT
    environment:
      - SPRING_REDIS_SENTINEL_MASTER=mymaster
      - SPRING_REDIS_SENTINEL_NODES=redis-sentinel:26379
      - SPRING_REDIS_SENTINEL_PASSWORD=P@ssw0rd
      - SPRING_REDIS_PASSWORD=P@ssw0rd
      - SPRING_REDIS_TIMEOUT=PT1S
      - SPRING_REDIS_CONNECT_TIMEOUT=PT0.5S
      - LOGGING_LEVEL_IO_LETTUCE=INFO
      - _JAVA_OPTIONS=-Dlogging.level.io.lettuce=DEBUG
    ports:
      - "9082:8080"
    depends_on:
      - redis-sentinel