version: '3.8'

services:
  db:
    image: mysql
    container_name: db-container
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: hla
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: hla
    volumes:
      - /Users/Shared/Docker/mysql/data:/var/lib/mysql
      - "./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=P@ssw0rd --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080