version: '3'
services:
  cdn-1:
    image: openresty/openresty:alpine-fat
    volumes:
      - ./nginx/nginx-cache.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/lua:/lua
      #      - ./cache-1:/data/nginx/cache
      - ./nginx/favicon.ico:/etc/nginx/html/favicon.ico
    ports:
      - "80"

  cdn-2:
    image: openresty/openresty:alpine-fat
    volumes:
      - ./nginx/nginx-cache.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/lua:/lua
      #      - ./cache-2:/data/nginx/cache
      - ./nginx/favicon.ico:/etc/nginx/html/favicon.ico
    ports:
      - "80"

  cdn-3:
    image: openresty/openresty:alpine-fat
    volumes:
      - ./nginx/nginx-cache.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/lua:/lua
      #      - ./cache-3:/data/nginx/cache
      - ./nginx/favicon.ico:/etc/nginx/html/favicon.ico
    ports:
      - "80"

  cdn-4:
    image: openresty/openresty:alpine-fat
    volumes:
      - ./nginx/nginx-cache.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/lua:/lua
      #      - ./cache-4:/data/nginx/cache
      - ./nginx/favicon.ico:/etc/nginx/html/favicon.ico
    ports:
      - "80"

  cdn-balancer:
    image: nginx:latest
    volumes:
      - ./nginx/nginx-balancer.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - cdn-1
      - cdn-2
      - cdn-3
      - cdn-4

  source:
    image: nginx:latest
    volumes:
      - ./nginx/nginx-images.conf:/etc/nginx/nginx.conf
      - ./images:/data/images
      - ./nginx/favicon.ico:/etc/nginx/html/favicon.ico
    ports:
      - "80"
