# Use postgres/example user/password credentials
version: '3'

services:
  main:
    image: postgres:13
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    env_file:
      - conf/db.env
    ports:
      - '5432:5432'
    volumes:
      - ./conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - vol-main:/var/lib/postgresql/data/
      - ./sql/main.sql:/docker-entrypoint-initdb.d/init.sql:ro

  shard_1:
    image: postgres:13
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    env_file:
      - conf/db.env
    ports:
      - '6432:5432'
    volumes:
      - ./conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - vol-shard_1:/var/lib/postgresql/data/
      - ./sql/shard_1.sql:/docker-entrypoint-initdb.d/init.sql:ro

  shard_2:
    image: postgres:13
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    env_file:
      - conf/db.env
    ports:
      - '7432:5432'
    volumes:
      - ./conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - vol-shard_2:/var/lib/postgresql/data/
      - ./sql/shard_2.sql:/docker-entrypoint-initdb.d/init.sql:ro

  standalone:
    image: postgres:13
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    env_file:
      - conf/db.env
    ports:
      - '8432:5432'
    volumes:
      - ./conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - vol-standalone:/var/lib/postgresql/data/
      - ./sql/standalone.sql:/docker-entrypoint-initdb.d/init.sql:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  vol-main:
  vol-shard_1:
  vol-shard_2:
  vol-standalone:

#volumes:
#  vol-main:
#    external: true
#  vol-shard_1:
#    external: true
#  vol-shard_2:
#    external: true
#  vol-standalone:
#    external: true