# Use postgres/example user/password credentials
version: '3.1'

services:
  main:
    image: postgres:13
    env_file:
      - main/db.env
    ports:
      - '5432:5432'
    volumes:
      - shard_1:/var/lib/postgresql/data/
      - ./sql/main.sql:/docker-entrypoint-initdb.d/init.sql:ro

  shard_1:
    image: postgres:13
    env_file:
      - main/db.env
    ports:
      - '6432:5432'
    volumes:
      - shard_2:/var/lib/postgresql/data/
      - ./sql/shard_1.sql:/docker-entrypoint-initdb.d/init.sql:ro

  shard_2:
    image: postgres:13
    env_file:
      - main/db.env
    ports:
      - '7432:5432'
    volumes:
      - shard_3:/var/lib/postgresql/data/
      - ./sql/shard_2.sql:/docker-entrypoint-initdb.d/init.sql:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  shard_1:
  shard_2:
  shard_3:
#  shard_1-sync:
#    external: true
#  shard_2-sync:
#    external: true
#  shard_3-sync:
#    external: true